export const TYPES = {
  EVENTS_ALL: 'EVENTS_ALL',
  BIRTHS_ALL: 'BIRTHS_ALL',
  DEATHS_ALL: 'DEATHS_ALL',
  EVENTS_ERROR: 'EVENTS_ERROR',
  BIRTHS_ERROR: 'BIRTHS_ERROR',
  DEATHS_ERROR: 'DEATHS_ERROR'
}
